before_script:
  - export ANDROID_HOME=/usr/local/share/android-sdk

stages:
  - test
  - build

check:
  stage: test
  script:
    - ./gradlew check
  tags:
    - android

buildDebug:
  stage: build
  script:
    - ./gradlew :android:assembleDebug
    - xcodebuild -workspace ./ios/TodoApp/TodoApp.xcworkspace -scheme TodoApp build
  tags:
    - android
