branches:
  only:
    - master
    - /^travis-.*$/
    - /^feature-.*$/
    - /^fix-.*$/

jobs:
  include:
    - name: Check style and android tests
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      jdk: oraclejdk8
      script:
        - ./gradlew ktlintCheck
        - ./gradlew detekt
        - ./gradlew :android:check

    - name: Check iOS interaction
      language: bash
      os: osx
      osx_image: xcode11.3
      script:
        - ./gradlew :interaction:macosTest

    - name: Check Android interaction
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      jdk: oraclejdk8
      script:
        - ./gradlew :interaction:androidTest

    - name: Check backend
      language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - build-tools-29.0.2
          - android-29
      script: ./gradlew :todo:check

    - name: Android build
      language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - build-tools-29.0.2
          - android-29
      script: ./gradlew :android:assembleDebug

    - name: iOS build
      language: bash
      os: osx
      osx_image: xcode11.3
      before_install:
        - brew install fastlane
      script:
        - ./gradlew packForXcode
        - cd ./ios/TodoApp
        - bundle update --bundler
        - fastlane beta
